name: dual_calendar
description: A beautiful dual calendar app with Gregorian and Hijri calendars
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  #
  # Calendar
  table_calendar: ^3.0.9
  hijri: ^3.0.0
  intl: 

  # Storage
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
